import { useEffect, useState } from "react"
import {
  FileText,
  Eye,
  Download,
  Printer,
  FileCheck,
  Clock,
  Users,
  TrendingUp,
  X,
  Search,
  ShieldCheck,
  CalendarDays,
  CheckCircle,
} from "lucide-react"

const demoReports = [
  {
    id: "R-5001",
    patientId: "P-1001",
    patientName: "Aarav Sharma",
    caseType: "General Consultation",
    date: "Today",
    status: "Generated",
  },
  {
    id: "R-5002",
    patientId: "P-1002",
    patientName: "Priya Patil",
    caseType: "Follow-up Case",
    date: "Today",
    status: "Generated",
  },
  {
    id: "R-5003",
    patientId: "P-1003",
    patientName: "Rahul Mehta",
    caseType: "Clinical Case",
    date: "Yesterday",
    status: "Generated",
  },
  {
    id: "R-5004",
    patientId: "P-1004",
    patientName: "Sneha Joshi",
    caseType: "General Consultation",
    date: "Yesterday",
    status: "Generated",
  },
  {
    id: "R-5005",
    patientId: "P-1005",
    patientName: "Vikram Shah",
    caseType: "Clinical Case",
    date: "2 days ago",
    status: "Generated",
  },
]

function Reports() {
  const [reports, setReports] = useState(demoReports)
  const [selectedReport, setSelectedReport] = useState(null)
  const [search, setSearch] = useState("")

  useEffect(() => {
    const loadReports = () => {
      const savedCases = JSON.parse(
        localStorage.getItem("medicase_cases") || "[]"
      )

      const savedReports = savedCases.map((item, index) => ({
        id: "R-" + (6000 + index),
        patientId: item.patientId,
        patientName: item.patientName,
        caseType: "AI Documentation Report",
        date: item.createdAt || "Today",
        status: "Generated",
        caseData: item,
      }))

      setReports([...savedReports, ...demoReports])
    }

    loadReports()

    window.addEventListener(
      "storage",
      loadReports
    )

    window.addEventListener(
      "medicase_cases_updated",
      loadReports
    )

    return () => {
      window.removeEventListener(
        "storage",
        loadReports
      )

      window.removeEventListener(
        "medicase_cases_updated",
        loadReports
      )
    }
  }, [])

  const filteredReports = reports.filter((report) => {
    const value = search.toLowerCase()

    return (
      report.id.toLowerCase().includes(value) ||
      report.patientName.toLowerCase().includes(value) ||
      report.patientId.toLowerCase().includes(value) ||
      report.caseType.toLowerCase().includes(value)
    )
  })

  const handleView = (report) => {
    setSelectedReport(report)
  }

  const handlePrint = () => {
    window.print()
  }

  const handleDownload = (report) => {
    const content = `
MEDICASE AI
CLINICAL DOCUMENTATION REPORT

Report ID: ${report.id}
Patient: ${report.patientName}
Patient ID: ${report.patientId}
Case Type: ${report.caseType}
Date: ${report.date}

This is a fictional demonstration report created using MediCase AI.

AI-generated documentation assistance.
Please verify all information before clinical use.

No diagnosis, prescription, or treatment recommendation
is generated by this prototype.
`

    const blob = new Blob([content], {
      type: "text/plain",
    })

    const url = URL.createObjectURL(blob)

    const link = document.createElement("a")

    link.href = url
    link.download =
      report.id + "-MediCase-Report.txt"

    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)

    URL.revokeObjectURL(url)
  }

  const generatedCount = reports.filter(
    (report) => report.status === "Generated"
  ).length

  const patientCount = new Set(
    reports.map((report) => report.patientId)
  ).size

  const todayCount = reports.filter(
    (report) => report.date === "Today"
  ).length

  return (
    <div className="max-w-7xl mx-auto space-y-6">

      {/* Header */}
      <div className="bg-white border border-slate-200 rounded-3xl shadow-sm p-5 sm:p-6">

        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-5">

          <div className="flex items-start gap-4">

            <div className="w-12 h-12 sm:w-14 sm:h-14 rounded-2xl bg-blue-50 flex items-center justify-center flex-shrink-0">
              <FileText
                size={27}
                className="text-blue-600"
              />
            </div>

            <div>

              <div className="flex flex-wrap items-center gap-2">

                <span className="px-2.5 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-bold">
                  DOCUMENTATION
                </span>

                <span className="px-2.5 py-1 rounded-full bg-green-50 text-green-700 text-xs font-bold flex items-center gap-1">
                  <CheckCircle size={13} />
                  {reports.length} Reports
                </span>

              </div>

              <h1 className="text-2xl sm:text-3xl font-bold text-slate-800 mt-3">
                Clinical Reports
              </h1>

              <p className="text-sm text-slate-500 mt-1 max-w-2xl">
                View, review, print, and download MediCase AI documentation reports.
              </p>

            </div>
          </div>

          <div className="flex items-center gap-2 bg-slate-50 border border-slate-200 rounded-xl px-4 py-3">

            <ShieldCheck
              size={18}
              className="text-green-600"
            />

            <div>
              <p className="text-xs font-semibold text-slate-500">
                Demo Mode
              </p>

              <p className="text-sm font-bold text-slate-700">
                Fictional Data Only
              </p>
            </div>

          </div>

        </div>
      </div>

      {/* Statistics */}
      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">

        <StatCard
          icon={FileCheck}
          label="Total Reports"
          value={reports.length}
          iconBox="bg-blue-50"
          iconColor="text-blue-600"
        />

        <StatCard
          icon={TrendingUp}
          label="Generated"
          value={generatedCount}
          iconBox="bg-green-50"
          iconColor="text-green-600"
        />

        <StatCard
          icon={Users}
          label="Patients"
          value={patientCount}
          iconBox="bg-purple-50"
          iconColor="text-purple-600"
        />

        <StatCard
          icon={Clock}
          label="Today's Reports"
          value={todayCount}
          iconBox="bg-orange-50"
          iconColor="text-orange-600"
        />

      </div>

      {/* Search */}
      <div className="bg-white border border-slate-200 rounded-2xl shadow-sm p-4 sm:p-5">

        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">

          <div>

            <h2 className="font-bold text-slate-800">
              Report Records
            </h2>

            <p className="text-sm text-slate-500 mt-1">
              Search reports by patient name, ID, or report ID.
            </p>

          </div>

          <div className="relative w-full sm:w-80">

            <Search
              size={18}
              className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"
            />

            <input
              type="text"
              value={search}
              onChange={(event) =>
                setSearch(event.target.value)
              }
              placeholder="Search reports..."
              className="w-full pl-10 pr-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100"
            />

          </div>

        </div>

        {search && (
          <div className="mt-3 text-xs text-slate-500">
            Showing {filteredReports.length} of {reports.length} reports
          </div>
        )}

      </div>

      {/* Desktop Table */}
      <div className="hidden lg:block bg-white border border-slate-200 rounded-3xl shadow-sm overflow-hidden">

        <div className="p-5 border-b border-slate-200 bg-slate-50/70">

          <div className="flex items-center justify-between">

            <div className="flex items-center gap-3">

              <div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center">
                <FileText
                  size={20}
                  className="text-blue-600"
                />
              </div>

              <div>
                <h2 className="font-bold text-slate-800">
                  Clinical Documentation Reports
                </h2>

                <p className="text-xs text-slate-500 mt-1">
                  {filteredReports.length} report records
                </p>
              </div>

            </div>

            <span className="px-3 py-1.5 rounded-full bg-green-50 text-green-700 text-xs font-semibold">
              All Systems Ready
            </span>

          </div>

        </div>

        <div className="overflow-x-auto">

          <table className="w-full">

            <thead className="bg-slate-50">

              <tr>

                <th className="text-left px-5 py-4 text-xs font-bold text-slate-500 uppercase tracking-wide">
                  Report
                </th>

                <th className="text-left px-5 py-4 text-xs font-bold text-slate-500 uppercase tracking-wide">
                  Patient
                </th>

                <th className="text-left px-5 py-4 text-xs font-bold text-slate-500 uppercase tracking-wide">
                  Case Type
                </th>

                <th className="text-left px-5 py-4 text-xs font-bold text-slate-500 uppercase tracking-wide">
                  Date
                </th>

                <th className="text-left px-5 py-4 text-xs font-bold text-slate-500 uppercase tracking-wide">
                  Status
                </th>

                <th className="text-right px-5 py-4 text-xs font-bold text-slate-500 uppercase tracking-wide">
                  Actions
                </th>

              </tr>

            </thead>

            <tbody className="divide-y divide-slate-100">

              {filteredReports.map((report) => (

                <tr
                  key={report.id}
                  className="hover:bg-blue-50/30 transition"
                >

                  <td className="px-5 py-4">

                    <div className="flex items-center gap-3">

                      <div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center">
                        <FileText
                          size={18}
                          className="text-blue-600"
                        />
                      </div>

                      <div>

                        <p className="font-bold text-slate-800">
                          {report.id}
                        </p>

                        <p className="text-xs text-slate-400">
                          MediCase AI
                        </p>

                      </div>

                    </div>

                  </td>

                  <td className="px-5 py-4">

                    <p className="font-semibold text-slate-800">
                      {report.patientName}
                    </p>

                    <p className="text-xs text-slate-500 mt-0.5">
                      {report.patientId}
                    </p>

                  </td>

                  <td className="px-5 py-4">

                    <span className="inline-flex px-3 py-1.5 rounded-lg bg-slate-100 text-slate-600 text-xs font-semibold">
                      {report.caseType}
                    </span>

                  </td>

                  <td className="px-5 py-4">

                    <div className="flex items-center gap-2 text-sm text-slate-600">
                      <CalendarDays size={15} />
                      {report.date}
                    </div>

                  </td>

                  <td className="px-5 py-4">

                    <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-green-50 text-green-700 text-xs font-bold">
                      <CheckCircle size={13} />
                      {report.status}
                    </span>

                  </td>

                  <td className="px-5 py-4">

                    <div className="flex justify-end gap-1">

                      <ActionButton
                        icon={Eye}
                        label="View"
                        onClick={() =>
                          handleView(report)
                        }
                        hoverClass="hover:bg-blue-50 hover:text-blue-600"
                      />

                      <ActionButton
                        icon={Printer}
                        label="Print"
                        onClick={handlePrint}
                        hoverClass="hover:bg-slate-100 hover:text-slate-700"
                      />

                      <ActionButton
                        icon={Download}
                        label="Download"
                        onClick={() =>
                          handleDownload(report)
                        }
                        hoverClass="hover:bg-green-50 hover:text-green-600"
                      />

                    </div>

                  </td>

                </tr>

              ))}

            </tbody>

          </table>

        </div>

        {filteredReports.length === 0 && (
          <EmptyReports />
        )}

      </div>

      {/* Mobile Cards */}
      <div className="lg:hidden space-y-4">

        {filteredReports.map((report) => (

          <div
            key={report.id}
            className="bg-white border border-slate-200 rounded-2xl shadow-sm p-4"
          >

            <div className="flex items-start justify-between gap-3">

              <div className="flex items-center gap-3">

                <div className="w-11 h-11 rounded-xl bg-blue-50 flex items-center justify-center flex-shrink-0">
                  <FileText
                    size={19}
                    className="text-blue-600"
                  />
                </div>

                <div>

                  <p className="font-bold text-slate-800">
                    {report.id}
                  </p>

                  <p className="text-xs text-slate-400 mt-0.5">
                    MediCase AI
                  </p>

                </div>

              </div>

              <span className="px-2.5 py-1 rounded-full bg-green-50 text-green-700 text-xs font-bold">
                Generated
              </span>

            </div>

            <div className="mt-4 grid grid-cols-2 gap-3">

              <div className="bg-slate-50 rounded-xl p-3">
                <p className="text-[11px] uppercase font-bold text-slate-400">
                  Patient
                </p>

                <p className="text-sm font-semibold text-slate-800 mt-1">
                  {report.patientName}
                </p>

                <p className="text-xs text-slate-500 mt-0.5">
                  {report.patientId}
                </p>
              </div>

              <div className="bg-slate-50 rounded-xl p-3">
                <p className="text-[11px] uppercase font-bold text-slate-400">
                  Date
                </p>

                <p className="text-sm font-semibold text-slate-800 mt-1">
                  {report.date}
                </p>
              </div>

            </div>

            <div className="mt-3">

              <p className="text-[11px] uppercase font-bold text-slate-400">
                Case Type
              </p>

              <p className="text-sm text-slate-600 mt-1">
                {report.caseType}
              </p>

            </div>

            <div className="flex gap-2 mt-4 pt-4 border-t border-slate-100">

              <button
                type="button"
                onClick={() =>
                  handleView(report)
                }
                className="flex-1 px-3 py-2.5 rounded-xl bg-blue-50 text-blue-700 text-sm font-semibold flex items-center justify-center gap-2"
              >
                <Eye size={16} />
                View
              </button>

              <button
                type="button"
                onClick={handlePrint}
                className="px-3 py-2.5 rounded-xl border border-slate-200 text-slate-600"
              >
                <Printer size={17} />
              </button>

              <button
                type="button"
                onClick={() =>
                  handleDownload(report)
                }
                className="px-3 py-2.5 rounded-xl border border-slate-200 text-slate-600"
              >
                <Download size={17} />
              </button>

            </div>

          </div>

        ))}

        {filteredReports.length === 0 && (
          <EmptyReports />
        )}

      </div>

      {/* Safety Notice */}
      <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 sm:p-5">

        <div className="flex items-start gap-3">

          <div className="w-9 h-9 rounded-xl bg-white flex items-center justify-center flex-shrink-0">
            <ShieldCheck
              size={19}
              className="text-amber-600"
            />
          </div>

          <div>

            <p className="font-bold text-amber-800">
              Demo Documentation
            </p>

            <p className="text-sm text-amber-700 mt-1 leading-6">
              Reports shown here use fictional demo data. AI-generated
              documentation must be reviewed and verified before clinical use.
            </p>

          </div>

        </div>

      </div>

      {/* Modal */}
      {selectedReport && (

        <div className="fixed inset-0 z-50 bg-slate-900/50 backdrop-blur-sm flex items-center justify-center p-3 sm:p-5">

          <div className="bg-white rounded-3xl shadow-2xl w-full max-w-3xl max-h-[92vh] overflow-hidden flex flex-col">

            {/* Modal Header */}
            <div className="p-5 border-b border-slate-200 flex items-center justify-between bg-white">

              <div className="flex items-center gap-3">

                <div className="w-11 h-11 rounded-xl bg-blue-50 flex items-center justify-center">
                  <FileText
                    size={20}
                    className="text-blue-600"
                  />
                </div>

                <div>

                  <h2 className="text-lg sm:text-xl font-bold text-slate-800">
                    Report Preview
                  </h2>

                  <p className="text-xs text-slate-500 mt-1">
                    {selectedReport.id} • MediCase AI
                  </p>

                </div>

              </div>

              <button
                type="button"
                onClick={() =>
                  setSelectedReport(null)
                }
                className="w-9 h-9 rounded-xl flex items-center justify-center text-slate-500 hover:bg-slate-100 transition"
              >
                <X size={20} />
              </button>

            </div>

            {/* Modal Content */}
            <div className="p-5 sm:p-7 overflow-y-auto">

              <div className="text-center border-b border-slate-200 pb-6">

                <div className="w-14 h-14 mx-auto rounded-2xl bg-blue-50 flex items-center justify-center">
                  <FileCheck
                    size={27}
                    className="text-blue-600"
                  />
                </div>

                <h1 className="text-2xl font-bold text-blue-700 mt-3">
                  MediCase AI
                </h1>

                <p className="text-sm text-slate-500 mt-1">
                  Smart Patient Case-Taking & Clinical Documentation
                </p>

                <h2 className="text-lg font-bold text-slate-800 mt-5">
                  Clinical Documentation Report
                </h2>

              </div>

              {/* Patient Details */}
              <div className="mt-6 grid grid-cols-1 sm:grid-cols-2 gap-3">

                <ModalInfo
                  label="Patient"
                  value={selectedReport.patientName}
                />

                <ModalInfo
                  label="Patient ID"
                  value={selectedReport.patientId}
                />

                <ModalInfo
                  label="Report ID"
                  value={selectedReport.id}
                />

                <ModalInfo
                  label="Date"
                  value={selectedReport.date}
                />

                <ModalInfo
                  label="Case Type"
                  value={selectedReport.caseType}
                />

                <ModalInfo
                  label="Status"
                  value={selectedReport.status}
                />

              </div>

              {/* Case Information */}
              {selectedReport.caseData && (

                <div className="mt-7">

                  <div className="flex items-center gap-2 mb-4">

                    <div className="w-8 h-8 rounded-lg bg-blue-50 flex items-center justify-center">
                      <FileText
                        size={16}
                        className="text-blue-600"
                      />
                    </div>

                    <h3 className="font-bold text-slate-800">
                      Recorded Case Information
                    </h3>

                  </div>

                  <div className="space-y-4">

                    <ReportSection
                      title="Chief Complaint"
                      value={
                        selectedReport.caseData.chiefComplaint
                      }
                    />

                    <ReportSection
                      title="Present History"
                      value={
                        selectedReport.caseData.presentHistory
                      }
                    />

                    <ReportSection
                      title="Medical History"
                      value={
                        selectedReport.caseData.medicalHistory
                      }
                    />

                    <ReportSection
                      title="Medicines"
                      value={
                        selectedReport.caseData.medicines
                      }
                    />

                    <ReportSection
                      title="Allergies"
                      value={
                        selectedReport.caseData.allergies
                      }
                    />

                    <ReportSection
                      title="Family History"
                      value={
                        selectedReport.caseData.familyHistory
                      }
                    />

                    <ReportSection
                      title="Lifestyle"
                      value={
                        selectedReport.caseData.lifestyle
                      }
                    />

                    <ReportSection
                      title="Clinical Examination"
                      value={
                        selectedReport.caseData.clinicalExamination
                      }
                    />

                  </div>

                </div>

              )}

              {/* Disclaimer */}
              <div className="mt-6 bg-amber-50 border border-amber-200 rounded-2xl p-4">

                <p className="text-sm font-bold text-amber-800">
                  Documentation Notice
                </p>

                <p className="text-xs text-amber-700 mt-1 leading-5">
                  AI-generated documentation assistance only. Please verify
                  all information before clinical use. This prototype does not
                  diagnose, prescribe, or recommend treatment.
                </p>

              </div>

            </div>

            {/* Modal Footer */}
            <div className="p-4 sm:p-5 border-t border-slate-200 bg-slate-50 flex flex-col sm:flex-row justify-end gap-2">

              <button
                type="button"
                onClick={handlePrint}
                className="px-4 py-2.5 rounded-xl border border-slate-200 bg-white font-semibold text-slate-700 flex items-center justify-center gap-2 hover:bg-slate-50"
              >
                <Printer size={17} />
                Print
              </button>

              <button
                type="button"
                onClick={() =>
                  handleDownload(selectedReport)
                }
                className="px-4 py-2.5 rounded-xl bg-blue-600 text-white font-semibold flex items-center justify-center gap-2 hover:bg-blue-700"
              >
                <Download size={17} />
                Download Report
              </button>

            </div>

          </div>

        </div>

      )}

    </div>
  )
}

function StatCard({
  icon: Icon,
  label,
  value,
  iconBox,
  iconColor,
}) {
  return (
    <div className="bg-white border border-slate-200 rounded-2xl shadow-sm p-5 hover:shadow-md transition">

      <div className="flex items-center gap-3">

        <div
          className={`w-11 h-11 rounded-xl ${iconBox} flex items-center justify-center`}
        >
          <Icon
            size={21}
            className={iconColor}
          />
        </div>

        <div>

          <p className="text-sm text-slate-500">
            {label}
          </p>

          <p className="text-2xl font-bold text-slate-800 mt-0.5">
            {value}
          </p>

        </div>

      </div>

    </div>
  )
}

function ActionButton({
  icon: Icon,
  label,
  onClick,
  hoverClass,
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      title={label}
      className={`w-9 h-9 rounded-lg flex items-center justify-center text-slate-500 transition ${hoverClass}`}
    >
      <Icon size={17} />
    </button>
  )
}

function ModalInfo({
  label,
  value,
}) {
  return (
    <div className="bg-slate-50 border border-slate-100 rounded-xl p-3.5">

      <p className="text-xs font-semibold text-slate-400 uppercase tracking-wide">
        {label}
      </p>

      <p className="text-sm font-bold text-slate-800 mt-1 break-words">
        {value || "N/A"}
      </p>

    </div>
  )
}

function ReportSection({
  title,
  value,
}) {
  return (
    <div>

      <p className="text-xs font-bold uppercase tracking-wide text-slate-400">
        {title}
      </p>

      <div className="mt-2 bg-slate-50 border border-slate-100 rounded-xl p-4">

        <p className="text-sm text-slate-700 leading-6 whitespace-pre-wrap">
          {value || "Not recorded"}
        </p>

      </div>

    </div>
  )
}

function EmptyReports() {
  return (
    <div className="p-10 text-center">

      <div className="w-14 h-14 mx-auto rounded-2xl bg-slate-100 flex items-center justify-center">
        <FileText
          size={25}
          className="text-slate-400"
        />
      </div>

      <h3 className="font-bold text-slate-700 mt-4">
        No reports found
      </h3>

      <p className="text-sm text-slate-500 mt-1">
        Try changing your search.
      </p>

    </div>
  )
}

export default Reports